import type { Job } from "../types";

export const JOBS: Job[] = [
  {
    id: "1",
    title: "Frontend Developer",
    location: "Remote",
    description:
      "Build responsive and accessible user interfaces using modern web technologies.",
    department: "Engineering",
    salaryRange: "₵80,000 - ₵120,000",
    postedDate: "2025-01-15",
  },
  {
    id: "2",
    title: "UX Designer",
    location: "Oyarifa, Accra",
    description: "Create intuitive user experiences and beautiful interfaces.",
    department: "Design",
    salaryRange: "₵70,000 - ₵110,000",
    postedDate: "2025-01-10",
  },
  {
    id: "3",
    title: "Backend Engineer",
    location: "Spintex, Accra",
    description: "Develop scalable server-side applications and APIs.",
    department: "Engineering",
    salaryRange: "₵90,000 - ₵140,000",
    postedDate: "2025-01-05",
  },
  {
    id: "4",
    title: "Product Manager",
    location: "Remote",
    description: "Lead product strategy and work with cross-functional teams.",
    department: "Product",
    salaryRange: "₵100,000 - ₵150,000",
    postedDate: "2025-01-01",
  },
  {
    id: "5",
    title: "DevOps Engineer",
    location: "East Legon, Accra",
    description: "Manage cloud infrastructure and CI/CD pipelines.",
    department: "Engineering",
    salaryRange: "₵85,000 - ₵130,000",
    postedDate: "2025-01-18",
  },
  {
    id: "6",
    title: "Data Analyst",
    location: "Remote",
    description: "Analyze business data and provide actionable insights.",
    department: "Analytics",
    salaryRange: "₵75,000 - ₵115,000",
    postedDate: "2025-01-12",
  },
  {
    id: "7",
    title: "Marketing Specialist",
    location: "Airport City, Accra",
    description: "Develop and execute digital marketing campaigns.",
    department: "Marketing",
    salaryRange: "₵65,000 - ₵95,000",
    postedDate: "2025-01-08",
  },
  {
    id: "8",
    title: "Mobile App Developer",
    location: "Remote",
    description: "Build cross-platform mobile applications with React Native.",
    department: "Engineering",
    salaryRange: "₵85,000 - ₵125,000",
    postedDate: "2025-01-20",
  },
  {
    id: "9",
    title: "HR Coordinator",
    location: "Cantonments, Accra",
    description: "Manage recruitment and employee relations.",
    department: "Human Resources",
    salaryRange: "₵60,000 - ₵90,000",
    postedDate: "2025-01-14",
  },
];
